<?php

class EmpleadoPlantilla extends Empleado
{
    private float $sueldo;
    private int $dietas;

    /**
     * @param string $nombre
     * @param string $apellido
     * @param string $numeroSeguridadSocial
     * @param float $sueldo
     * @param int $dietas
     */

    public function __construct(string $nombre, string $apellido, string $numeroSeguridadSocial, float $sueldo, int $dietas)
    {
        parent::__construct($nombre,$apellido,$numeroSeguridadSocial);
        $this->sueldo = $sueldo;
        $this->dietas = $dietas;
    }

    /**
     * @return int
     */
    public function getSueldo(): int
    {
        return $this->sueldo;
    }

    /**
     * @param float $sueldo
     */
    public function setSueldo(float $sueldo): void
    {
        $this->sueldo = $sueldo;
    }

    /**
     * @return int
     */
    public function getDietas(): int
    {
        return $this->dietas;
    }

    /**
     * @param int $dietas
     */
    public function setDietas(int $dietas): void
    {
        $this->dietas = $dietas;
    }

    public function mostrar(): string
    {
        return parent::mostrar() . "sueldo: " . $this->sueldo . "€, dietas: " . $this->dietas . "€"; // TODO: Change the autogenerated stub
    }


    public function ingresos()
    {
        return $this->sueldo + $this->dietas;
    }


}